[package]
name = "ztw-runtime"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ztw-host-js"
path = "src/main.rs"

[dependencies]
ztw-api = { path = "../api" }
rquickjs = { version = "0.13", features = ["bindgen", "allocator", "loader"] }
serde_json = { version = "1", features = ["raw_value"] }

[dev-dependencies]
ztw-model = { path = "../model" }
ztw-sim = { path = "../sim" }
