[package]
name = "ztw-runtime-py"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ztw-host-py"
path = "src/main.rs"

[dependencies]
ztw-api = { path = "../api" }
pyo3 = { version = "0.29", features = ["auto-initialize"] }
serde_json = { version = "1", features = ["raw_value"] }

[dev-dependencies]
ztw-model = { path = "../model" }
ztw-sim = { path = "../sim" }
